# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Jared Sorge"
tagline: ""
description: "Follow <a href=\"https://micro.blog/jsorge\">@jsorge on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/jsorge\">@jsorge on Micro.blog</a>."
baseurl: ""
url: "https://mb.jsorge.net"
markdown: "kramdown"
username: "jsorge"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Jared Sorge"
name: "Jared Sorge"
gravatar_hash: "8a3595f02554f79bffcb64f657f507cf"
avatar: "https://micro.blog/jsorge/avatar.jpg"
full_name: "Jared Sorge"
bio: ""
twitter_username: "jsorge"
github_username: "jsorge"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "373"